-- MySQL Script generated by MySQL Workbench
-- Tue Sep 12 01:15:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema osbb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema osbb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `osbb` DEFAULT CHARACTER SET utf8 ;
USE `osbb` ;

-- -----------------------------------------------------
-- Table `osbb`.`buildings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `osbb`.`buildings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `building_number` VARCHAR(45) NOT NULL,
  `number_of_apartments` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `osbb`.`apartments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `osbb`.`apartments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `apartment_number` VARCHAR(45) NOT NULL,
  `floor` INT NOT NULL,
  `area` FLOAT NOT NULL,
  `building_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_builging_idx` (`building_id` ASC) VISIBLE,
  CONSTRAINT `fk_builging`
    FOREIGN KEY (`building_id`)
    REFERENCES `osbb`.`buildings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `osbb`.`osbb_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `osbb`.`osbb_members` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `osbb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `osbb`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_name` ENUM('member', 'worker', 'member of department', 'head of department') NOT NULL DEFAULT 'member',
  `members_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `index_role` (`role_name` ASC) VISIBLE,
  UNIQUE INDEX `members_id_UNIQUE` (`members_id` ASC) VISIBLE,
  CONSTRAINT `fk_role2member`
    FOREIGN KEY (`members_id`)
    REFERENCES `osbb`.`osbb_members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `osbb`.`rc_residents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `osbb`.`rc_residents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `car_permission` TINYINT NULL DEFAULT 0,
  `member_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_residents2members_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_residents2members`
    FOREIGN KEY (`member_id`)
    REFERENCES `osbb`.`osbb_members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `osbb`.`ownership_rights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `osbb`.`ownership_rights` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `member_id` INT NOT NULL,
  `apartment_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_member_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_apartment_idx` (`apartment_id` ASC) VISIBLE,
  CONSTRAINT `fk_member`
    FOREIGN KEY (`member_id`)
    REFERENCES `osbb`.`osbb_members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_apartment`
    FOREIGN KEY (`apartment_id`)
    REFERENCES `osbb`.`apartments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `osbb`.`residents_living`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `osbb`.`residents_living` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `resident_id` INT NOT NULL,
  `apartment_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_apartment_idx` (`apartment_id` ASC) VISIBLE,
  INDEX `fk_resident_idx` (`resident_id` ASC) VISIBLE,
  CONSTRAINT `fk_apartment_member`
    FOREIGN KEY (`apartment_id`)
    REFERENCES `osbb`.`apartments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resident`
    FOREIGN KEY (`resident_id`)
    REFERENCES `osbb`.`rc_residents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;